version: '3'

services:
  database:
    image: mysql:${MYSQL_VERSION:-8.0.30}-debian
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-db_name}
      MYSQL_USER: ${MYSQL_USER:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-SFSAfd3212SFa32rtg3fwerh}
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data:
