version: '3.2'

services:
  database:
    image: mysql:${MYSQL_VERSION:-8.0.30}-debian
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-db_name}
      MYSQL_USER: ${MYSQL_USER:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-SFSAfd3212SFa32rtg3fwerh}
    volumes:
      - db-data:/var/lib/mysql:rw

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://db_user:db_password@database:3306/db_name?serverVersion=5.7&charset=utf8mb4

volumes:
  db-data:
